import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { StyledRoot } from "./theme";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledRoot>{children}</StyledRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
